include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    argument_type_not_assignable: ignore

exclude:
  - 'flutter_aad/*'
linter:
  rules:
    avoid_void_async: true
    avoid_print: true
    prefer_single_quotes: true
    avoid_types_on_closure_parameters: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    package_api_docs: true
    package_prefixed_library_names: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    prefer_const_constructors: false
